### ISSUE TITLE
HTTP_Upgrade not capitalized

### ISSUE THREAD

**Issue by dfee** [housleyjk/aiopyramid#18]
A non-modified pyramid project from the template aio_websocket is breaking at [aiopyramid/websocket/config/gunicorn.py:81](https://github.com/housleyjk/aiopyramid/blob/master/aiopyramid/websocket/config/gunicorn.py#L81)

The problem is that the code is expecting `environ` to have `HTTP_UPGRADE` but it actually has `HTTP_Upgrade` (titlecase).

Is this a problem with aiopyramid?

**Comment by housleyjk** [comment]
Just to clarify. You are saying that the code is putting `HTTP_UPGRADE` in the environ when it should be `HTTP_Upgrade`? The call to `k.upper()` should uppercase the entire string not title it. What is the error you are seeing?

**Comment by dfee** [comment]
I'm seeing this as a stacktrace:

`2016-09-19 23:40:08,879 INFO  [gunicorn.access:116][MainThread] 172.18.0.1 - - [19/Sep/2016:23:40:08 +0000] "GET / HTTP/1.1" 200 - "-" "-"
2016-09-19 23:40:09,343 ERROR [gunicorn.error:253][MainThread] Error handling request
Traceback (most recent call last):
  File "/var/www/myproj/env/lib/python3.5/site-packages/websockets/handshake.py", line 85, in check_request
    assert get_header('Upgrade').lower() == 'websocket'
  File "/var/www/myproj/env/lib/python3.5/site-packages/aiopyramid/websocket/config/gunicorn.py", line 81, in get_header
    return environ['HTTP_' + k.upper().replace('-', '_')]
KeyError: 'HTTP_UPGRADE'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/www/myproj/env/lib/python3.5/site-packages/aiohttp/server.py", line 261, in start
    yield from self.handle_request(message, payload)
  File "/var/www/myproj/env/lib/python3.5/site-packages/aiopyramid/gunicorn/worker.py", line 87, in handle_request
    response.start_response
  File "/var/www/myproj/env/lib/python3.5/site-packages/aiopyramid/helpers.py", line 48, in spawn_greenlet
    result = g.switch(*args, **kwargs)
  File "/var/www/myproj/env/lib/python3.5/site-packages/pyramid/router.py", line 236, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/var/www/myproj/env/lib/python3.5/site-packages/pyramid/router.py", line 211, in invoke_subrequest
    response = handle_request(request)
  File "/var/www/myproj/env/lib/python3.5/site-packages/pyramid_debugtoolbar/toolbar.py", line 187, in toolbar_tween
    return handler(request)
  File "/var/www/myproj/env/lib/python3.5/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/var/www/myproj/env/lib/python3.5/site-packages/pyramid/compat.py", line 148, in reraise
    raise value
  File "/var/www/myproj/env/lib/python3.5/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/var/www/myproj/env/lib/python3.5/site-packages/pyramid/router.py", line 158, in handle_request
    view_name
  File "/var/www/myproj/env/lib/python3.5/site-packages/pyramid/view.py", line 547, in _call_view
    response = view_callable(context, request)
  File "/var/www/myproj/env/lib/python3.5/site-packages/pyramid/viewderivers.py", line 413, in viewresult_to_response
    result = view(context, request)
  File "/var/www/myproj/env/lib/python3.5/site-packages/aiopyramid/websocket/config/gunicorn.py", line 132, in websocket_view
    switch_protocols,
  File "/var/www/myproj/env/lib/python3.5/site-packages/aiopyramid/websocket/config/gunicorn.py", line 83, in __init__
    key = websockets.handshake.check_request(get_header)
  File "/var/www/myproj/env/lib/python3.5/site-packages/websockets/handshake.py", line 93, in check_request
    raise InvalidHandshake("Invalid request") from exc
websockets.exceptions.InvalidHandshake: Invalid request
2016-09-19 23:40:09,363 ERROR [asyncio:1148][MainThread] Task exception was never retrieved
future: <Task finished coro=<ServerHttpProtocol.start() done, defined at /var/www/myproj/env/lib/python3.5/site-packages/aiohttp/server.py:207> exception=AttributeError("'NoneType' object has no attribute 'get'",)>
Traceback (most recent call last):
  File "/var/www/myproj/env/lib/python3.5/site-packages/websockets/handshake.py", line 85, in check_request
    assert get_header('Upgrade').lower() == 'websocket'
  File "/var/www/myproj/env/lib/python3.5/site-packages/aiopyramid/websocket/config/gunicorn.py", line 81, in get_header
    return environ['HTTP_' + k.upper().replace('-', '_')]
KeyError: 'HTTP_UPGRADE'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/www/myproj/env/lib/python3.5/site-packages/aiohttp/server.py", line 261, in start
    yield from self.handle_request(message, payload)
  File "/var/www/myproj/env/lib/python3.5/site-packages/aiopyramid/gunicorn/worker.py", line 87, in handle_request
    response.start_response
  File "/var/www/myproj/env/lib/python3.5/site-packages/aiopyramid/helpers.py", line 48, in spawn_greenlet
    result = g.switch(*args, **kwargs)
  File "/var/www/myproj/env/lib/python3.5/site-packages/pyramid/router.py", line 236, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/var/www/myproj/env/lib/python3.5/site-packages/pyramid/router.py", line 211, in invoke_subrequest
    response = handle_request(request)
  File "/var/www/myproj/env/lib/python3.5/site-packages/pyramid_debugtoolbar/toolbar.py", line 187, in toolbar_tween
    return handler(request)
  File "/var/www/myproj/env/lib/python3.5/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/var/www/myproj/env/lib/python3.5/site-packages/pyramid/compat.py", line 148, in reraise
    raise value
  File "/var/www/myproj/env/lib/python3.5/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/var/www/myproj/env/lib/python3.5/site-packages/pyramid/router.py", line 158, in handle_request
    view_name
  File "/var/www/myproj/env/lib/python3.5/site-packages/pyramid/view.py", line 547, in _call_view
    response = view_callable(context, request)
  File "/var/www/myproj/env/lib/python3.5/site-packages/pyramid/viewderivers.py", line 413, in viewresult_to_response
    result = view(context, request)
  File "/var/www/myproj/env/lib/python3.5/site-packages/aiopyramid/websocket/config/gunicorn.py", line 132, in websocket_view
    switch_protocols,
  File "/var/www/myproj/env/lib/python3.5/site-packages/aiopyramid/websocket/config/gunicorn.py", line 83, in __init__
    key = websockets.handshake.check_request(get_header)
  File "/var/www/myproj/env/lib/python3.5/site-packages/websockets/handshake.py", line 93, in check_request
    raise InvalidHandshake("Invalid request") from exc
websockets.exceptions.InvalidHandshake: Invalid request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/var/www/myproj/env/lib/python3.5/site-packages/aiohttp/server.py", line 288, in start
    yield from self.handle_error(500, message, None, exc)
  File "/var/www/myproj/env/lib/python3.5/site-packages/aiohttp/server.py", line 345, in handle_error
    self.log_access(message, None, response, self._loop.time() - now)
  File "/var/www/myproj/env/lib/python3.5/site-packages/aiopyramid/gunicorn/worker.py", line 113, in log_access
    datetime.timedelta(0, 0, time))
  File "/var/www/myproj/env/lib/python3.5/site-packages/aiopyramid/gunicorn/worker.py", line 22, in atoms
    'h': environ.get('REMOTE_ADDR', '-'),
AttributeError: 'NoneType' object has no attribute 'get'`

`environ` looks like this:
`{'SERVER_PROTOCOL': 'HTTP/1.1', 'HTTP_Sec_Websocket_Extensions': 'permessage-deflate; client_max_window_bits', 'wsgi.input': <_io.BytesIO object at 0x7fc2b767a9e8>, 'HTTP_Pragma': 'no-cache', 'HTTP_Dnt': '1', 'SERVER_NAME': 'localhost', 'HTTP_Cache_Control': 'no-cache', 'async.writer': <StreamWriter transport=<_SelectorSocketTransport fd=22 read=polling write=<idle, bufsize=0>> reader=<aiohttp.parsers.StreamParser object at 0x7fc2b767cd68>>, 'SERVER_PORT': '6543', 'HTTP_Sec_Websocket_Version': '13', 'REQUEST_METHOD': 'GET', 'HTTP_Cookie': '_ga=GA1.1.2010304951.1473841800', 'REMOTE_ADDR': '172.18.0.1', 'HTTP_Sec_Websocket_Key': 'BSId7zxbU/CWLH2G9Tsrlg==', 'SCRIPT_NAME': '', 'wsgi.errors': <_io.TextIOWrapper name='<stderr>' mode='w' encoding='UTF-8'>, 'async.protocol': <aiopyramid.gunicorn.worker.AiopyramidHttpServerProtocol object at 0x7fc2b767ce80>, 'wsgi.url_scheme': 'http', 'wsgi.multiprocess': False, 'wsgi.async': True, 'async.reader': <aiohttp.parsers.StreamParser object at 0x7fc2b767cd68>, 'HTTP_Host': 'localhost:6543', 'SERVER_SOFTWARE': 'Python/3.5 aiohttp/1.0.1', 'wsgi.file_wrapper': <class 'aiohttp.wsgi.FileWrapper'>, 'HTTP_User_Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36', 'wsgi.multithread': False, 'HTTP_Accept_Language': 'en-US,en;q=0.8', 'wsgi.run_once': False, 'RAW_URI': '/echo', 'HTTP_Accept_Encoding': 'gzip, deflate, sdch', 'REMOTE_PORT': '43900', 'wsgi.version': (1, 0), 'PATH_INFO': '/echo', 'HTTP_Upgrade': 'websocket', 'HTTP_Origin': 'http://localhost:6543', 'HTTP_Connection': 'Upgrade', 'QUERY_STRING': ''}`

**Comment by dfee** [comment]
So, while the code expects `HTTP_UPGRADE`, we actually have `HTTP_Upgrade` in the request.

**Comment by dfee** [comment]
Maybe better questions are:

1. why aren't you expecting a non-caps HTTP_UPGRADE?
2. why isn't my HTTP_Upgrade capitalized?

**Comment by dfee** [comment]
Regardless, created a simple pull-request that fixes the problem. https://github.com/housleyjk/aiopyramid/pull/19

**Comment by housleyjk** [comment]
I will test and deploy.

**Comment by dfee** [comment]
@housleyjk let me know if you need anything before publishing this to pypi.

**Comment by housleyjk** [comment]
Thank you. I've run the tests, and I've just got to find time to run through packaging it up.

**Comment by amilstead** [comment]
Is it possible that this is related to an aiohttp + multidict version incompatibility with pyramid?

I've seen myself that multidict >2.0 breaks a not insignificant amount of core pyramid code in and around request processing. As far as I can tell it's due to this new multidict awkwardly title casing instead keys instead of real case insensitivity. See here: https://github.com/aio-libs/multidict/releases/tag/v2.0.0

From what I can tell it's due to the way pyramid imports certain libraries, effectively multidict ends up being patched in place of what it expects, which is no longer compatible due to the title case change. 
 
Versions of aiohttp > 0.22.5 will have this version of multidict and therefore potentially break things. @dfee what version of aiohttp do you have installed?

Also shout out to @houselyjk this library is awesome and I really appreciate your work. I look forward to contributing!

**Comment by dfee** [comment]
aiohttp version 1.0.2

**Comment by housleyjk** [comment]
This should be fixed now in the latest version from pypi. I wouldn't be surprised if it is an issue in pyramid, but I believe the fix as implemented should solve the problem for other headers.
