### ISSUE TITLE
Can't handle POST params

### ISSUE THREAD

**Issue by NeonMonk** [housleyjk/aiopyramid#6]
Whenever I try to get POST params. I get the following error.

This also happens before the view callable if pyramid_debugtoolbar is installed:

    import asyncio

    from pyramid.view import view_config
    from pyramid.response import Response

    html = """
    <head>

    <title>asyncio test</title>
    <META HTTP-EQUIV="Pragma" CONTENT="no-cache"> 
    <META HTTP-EQUIV="Expires" CONTENT="-1">
    </head>
    <body class="">
    {body}
    </body>
    """

    @view_config(route_name='say_hello')
    def say_hello(request):
      wait_time = float(request.params.get('sleep', 0.1))
      yield from asyncio.sleep(wait_time)

      return Response(html.format(body=request.params.get('content')))

Traceback:

    Error handling request
    Traceback (most recent call last):
      File "/usr/local/python/env/lib/python3.4/site-packages/aiohttp/server.py", line 240, in start
        yield from handler
      File "/usr/local/python/env/lib/python3.4/site-packages/aiopyramid/gunicorn/worker.py", line 33, in handle_request
        response.start_response
      File "/usr/local/python/env/lib/python3.4/site-packages/aiopyramid/helpers.py", line 51, in spawn_greenlet
        result = yield from result
      File "/usr/lib/python3.4/asyncio/futures.py", line 388, in __iter__
        yield self  # This tells Task to wait for completion.
      File "/usr/lib/python3.4/asyncio/tasks.py", line 286, in _wakeup
        value = future.result()
      File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
        raise self._exception
      File "/usr/lib/python3.4/asyncio/tasks.py", line 237, in _step
        result = next(coro)
      File "/usr/local/python/env/lib/python3.4/site-packages/aiopyramid/helpers.py", line 72, in run_in_greenlet
        return back.switch()
      File "/usr/local/python/env/lib/python3.4/site-packages/pyramid-1.5.2-py3.4.egg/pyramid/router.py", line 242, in __call__
        response = self.invoke_subrequest(request, use_tweens=True)
      File "/usr/local/python/env/lib/python3.4/site-packages/pyramid-1.5.2-py3.4.egg/pyramid/router.py", line 217, in invoke_subrequest
        response = handle_request(request)
      File "/usr/local/python/env/lib/python3.4/site-packages/pyramid-1.5.2-py3.4.egg/pyramid/tweens.py", line 21, in excview_tween
        response = handler(request)
      File "/usr/local/python/env/lib/python3.4/site-packages/pyramid-1.5.2-py3.4.egg/pyramid/router.py", line 163, in handle_request
        response = view_callable(context, request)
      File "/usr/local/python/env/lib/python3.4/site-packages/pyramid-1.5.2-py3.4.egg/pyramid/config/views.py", line 385, in viewresult_to_response
        result = view(context, request)
      File "/usr/local/python/env/lib/python3.4/site-packages/aiopyramid/helpers.py", line 121, in _wrapped_coroutine
        return future.result()
      File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
        raise self._exception
      File "/usr/local/python/env/lib/python3.4/site-packages/aiopyramid/helpers.py", line 66, in run_in_greenlet
        result = yield from func(*args, **kwargs)
      File "/usr/lib/python3.4/asyncio/coroutines.py", line 143, in coro
        res = yield from res
      File "/usr/local/websites/test/test/views.py", line 25, in say_hello
        wait_time = float(request.params.get('sleep', 0.1))
      File "/usr/local/python/env/lib/python3.4/site-packages/WebOb-1.4-py3.4.egg/webob/request.py", line 856, in params
        params = NestedMultiDict(self.GET, self.POST)
      File "/usr/local/python/env/lib/python3.4/site-packages/WebOb-1.4-py3.4.egg/webob/request.py", line 800, in POST
        encoding='utf8')
      File "/usr/lib/python3.4/cgi.py", line 557, in __init__
        self.read_urlencoded()
      File "/usr/lib/python3.4/cgi.py", line 660, in read_urlencoded
        qs = self.fp.read(self.length)
      File "/usr/local/python/env/lib/python3.4/site-packages/WebOb-1.4-py3.4.egg/webob/request.py", line 1546, in readinto
        sz = len(data)
    TypeError: object of type 'generator' has no len()

**Comment by NeonMonk** [comment]
Never mind. This was fixed by uninstall pip version & reinstalling from git clone.
