### ISSUE TITLE
Socket closing causes uWSGI worker to crash

### ISSUE THREAD

**Issue by NeonMonk** [housleyjk/aiopyramid#7]
When a client disconnects from the websockets, this happens:

    Respawned uWSGI worker 1 (new pid: 59479)
    *** running asyncio loop engine [addr:0x491ca0] ***
    Traceback (most recent call last):
      File "/usr/local/project/env/lib/python3.4/site-packages/pyramid-1.5.2-py3.4.egg/pyramid/router.py", line 242, in $
        response = self.invoke_subrequest(request, use_tweens=True)
      File "/usr/local/project/env/lib/python3.4/site-packages/pyramid-1.5.2-py3.4.egg/pyramid/router.py", line 217, in $
        response = handle_request(request)
      File "/usr/local/project/env/lib/python3.4/site-packages/pyramid-1.5.2-py3.4.egg/pyramid/tweens.py", line 21, in e$
        response = handler(request)
      File "/usr/local/project/env/lib/python3.4/site-packages/pyramid-1.5.2-py3.4.egg/pyramid/router.py", line 163, in $
        response = view_callable(context, request)
      File "/usr/local/project/env/lib/python3.4/site-packages/pyramid-1.5.2-py3.4.egg/pyramid/config/views.py", line 38$
        result = view(context, request)
      File "/usr/local/project/env/lib/python3.4/site-packages/aiopyramid-0.3.0-py3.4.egg/aiopyramid/websocket/config/uw$
        raise WebsocketClosed
    aiopyramid.websocket.exceptions.WebsocketClosed
    [pid: 59479|app: 0|req: 4/2] 192.168.1.189 () {46 vars in 1126 bytes} [Tue Jan 27 15:06:21 2015] GET /project/ws => $
    ...The work of process 59479 is done. Seeya!
    worker 1 killed successfully (pid: 59479)
    Respawned uWSGI worker 1 (new pid: 59501)

uWSGI chokes on raise WebsocketClosed. The worker gets killed & all of my websockets connections get disconnected. It's a pain to have to reconnect them. Is there something I'm missing?

**Comment by NeonMonk** [comment]
I should learn to read the docs more closely. Just read the "uWSGI Special Note"

Thank you for an awesome project.

**Comment by NeonMonk** [comment]
Actually, even when wrapped in  I still get:

    [pid: 60221|app: 0|req: 2/1] 192.168.1.189 () {46 vars in 1126 bytes} [Tue Jan 27 15:28:15 2015] GET /ws => $
    ...The work of process 60221 is done. Seeya!
    worker 1 killed successfully (pid: 60221)
    Respawned uWSGI worker 1 (new pid: 60264)

Is there a way to stop uwsgi from killing the worker until all clients are disconnected?

**Comment by housleyjk** [comment]
Thank you for finding this. However, I'm not able to replicate this with the basic websocket scaffold. For me, the process is never killed. 

    enabled greenlet engine
    *** uWSGI is running in multiple interpreter mode ***
    spawned uWSGI master process (pid: 4819)
    spawned uWSGI worker 1 (pid: 4823, cores: 50)
    *** running asyncio loop engine [addr:0x48e550] ***
    Python auto-reloader enabled
    [pid: 4823|app: 0|req: 1/1] 127.0.0.1 () {32 vars in 744 bytes} [Tue Jan 27 08:48:49 2015] GET / => generated 1602 bytes in 121 msecs (HTTP/1.1 200) 2 headers in 81 bytes (2 switches on core 49)
    Traceback (most recent call last):
      File "/home/housl/.env/aiotutorial/lib/python3.4/site-packages/pyramid/router.py", line 242, in __call__
        response = self.invoke_subrequest(request, use_tweens=True)
      File "/home/housl/.env/aiotutorial/lib/python3.4/site-packages/pyramid/router.py", line 217, in invoke_subrequest
        response = handle_request(request)
      File "/home/housl/.env/aiotutorial/lib/python3.4/site-packages/pyramid/tweens.py", line 21, in excview_tween
        response = handler(request)
      File "/home/housl/.env/aiotutorial/lib/python3.4/site-packages/pyramid/router.py", line 163, in handle_request
        response = view_callable(context, request)
      File "/home/housl/.env/aiotutorial/lib/python3.4/site-packages/pyramid/config/views.py", line 385, in viewresult_to_response
        result = view(context, request)
      File "/home/housl/.env/aiotutorial/lib/python3.4/site-packages/aiopyramid/websocket/config/uwsgi.py", line 83, in websocket_view
        raise WebsocketClosed
    aiopyramid.websocket.exceptions.WebsocketClosed
    [pid: 4823|app: 0|req: 2/2] 127.0.0.1 () {44 vars in 931 bytes} [Tue Jan 27 08:48:49 2015] GET /echo => generated 23 bytes in 173 msecs (HTTP/1.1 101) 4 headers in 184 bytes (0 switches on core 49)
    [pid: 4823|app: 0|req: 3/3] 127.0.0.1 () {34 vars in 775 bytes} [Tue Jan 27 08:49:05 2015] GET / => generated 1602 bytes in 102 msecs (HTTP/1.1 200) 2 headers in 81 bytes (2 switches on core 48)

Will you post the uwsgi section of your config file or the command you are using to launch uwsgi? Also, please send the view code and routing code for the ws route in your system. This will hopefully help us find what is causing that process to reset.

**Comment by housleyjk** [comment]
I am going to close this for now since I can't replicate it. Please reopen the ticket when you have more information about what is going on, and I will help you fix it or update the library to solve the bug.
